function k_e = beam_stiffness(IN,L)

    k_e = (IN.E * IN.I / L^3) * [ ...
         12,      6*L,    -12,     6*L; ...
         6*L,  4*L^2,   -6*L,  2*L^2; ...
        -12,     -6*L,     12,    -6*L; ...
         6*L,  2*L^2,   -6*L,  4*L^2 ];
end